# Permalinks
permalink:           pretty

# Setup
title:               Mlsic
tagline:             A computer music blog
description:         >
  A computer ğŸ–¥ï¸ music ğŸ¶ blog by <a href="https://github.com/bh90210" target="_blank">@bh90210</a>.
url:                 https://bh90210.github.io
paginate:            5
baseurl:             "/mlsic"

# Assets
sass:
  style:            compressed

# About/contact
author:
  name:              Byron Chris
  url:               https://bh90210.github.io
  email:             ktc@pm.me

# Custom vars
version:             2.1.0
github:
  repo:              https://github.com/bh90210/mlsic

markdown: kramdown

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist